apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "javadaprchart.fullname" . }}-conf
  labels:
    {{- include "javadaprchart.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}
  application.properties: |+
    {{ tpl (.Files.Get "files/application.properties") . | nindent 4 }}
  applicationinsights.json: |+
    {{ tpl (.Files.Get "files/applicationinsights.json") . | nindent 4 }}  