apiVersion: v1
kind: Service
metadata:
  name: {{ include "javadaprchart.fullname" . }}
  labels:
    {{- include "javadaprchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "javadaprchart.selectorLabels" . | nindent 4 }}
    app: app0002
    version: v1
